export const TOGGLE_CART = "TOGGLE_CART"
export const ADD_ITEM= "ADD_ITEM"


export const REMOVE_ITEM = "REMOVE_ITEM"

export const INCRESE_QUANTITY = "INCRESE_QUANTITY"
export const DECRESE_QUANTITY = "DECRESE_QUANTITY"

